---
-

  hosts: iperf_server
  tasks:
    - name: start server iperf 5000
      shell: iperf3 --server --one-off --daemon -p 5000
    - name: start server iperf 5002
      shell: iperf3 --server --one-off --daemon -p 5002



- hosts: iperf_client1
  tasks:

    - name: start server iperf 5008
      shell: iperf3 --server --one-off --daemon -p 5008
    - name:  start iperf client
      shell: iperf3 -c 192.168.1.173 -p 5000 -t 100 --logfile /root/iperf.txt

- hosts: iperf_client2
  tasks:
    - name: start server iperf 5010
      shell: iperf3 --server --one-off --daemon -p 5010
    - name:  start iperf client
      shell: iperf3 -c 192.168.1.173 -p 5002 -t 100 --logfile /root/iperf.txt
    # This block is for verbose purpose
      register: results
    - name: display results
      debug:
         msg: "{{ results }}"

