---
-
# This playbook is to install and run Iperf

  name:  Update system and install few apps
  hosts: all
  become: false
  
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest

    - name: Update all packages to the latest version
      apt:
        upgrade: dist 

    - name: Install a list of packages
      apt:
        pkg:
         - iperf3

    - name:  Start Iperf Server on port 5000
      hosts: iperf_server
    - shell: iperf3 -s -p 5000 >> /root/iperf3.log

    - name:  Start Client on port 5000
      hosts: iperf_client

    - name:  Start Client
      shell: iperf3 -c 192.168.1.165 -p 5000 -t 20  >> /root/iperf3.log