---
-
# This playbook is to install and run Iperf

  name:  Update system and install few apps
  hosts: iperf_server:iperf_client
  become: false
  strategy: free

  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest

    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Install a list of packages
      apt:
        pkg:
         - iperf3
