---
# For documentation please follow the link https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html 
- name: Update ubuntu servers 
  hosts: all
  remote_user: root
  become: true
  become_user: root
  become_method: su
  tasks:
    - name:  Update all packages to latest version 
      apt:
        upgrade: dist
    
    - name: Upgrade all packages to the latest version 
      apt:
        name:  "*"
        state: latest
    
    - name:  Remove garbage packages from the cache 
      apt:
         autoclean: yes
    
    
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Reboot the machine (Wait for 5 min)
      reboot:
        reboot_timeout: 30