---
-
  name: Update ubuntu system and install apps
  hosts: all
  become: true
  become_method: sudo

  pre_tasks:
    - name:  Update apt cache if needed.
      apt: 
        update_cache: true
        cache_valid_time: 3600
    
  tasks: 
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest

    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
    
    - name:  Install vim, net-tool, tree,
      apt:
        pkg:
        - vim
        - tree
        - net-tools


    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required_file

    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
    # - name:  Reboot System (mandatory reboot, uncomment to enable this  option)
    #   command: sudo reboot